- name: Frontend setup
  hosts: FRONTEND
  become: yes
  roles:
    - frontend

- name: mongodb setup
  hosts: MONGODB
  become: yes
  roles:
    - mongodb
- name: catalouge
  hosts: CATAlOUGE
  become: yes
  role:
    - catalouge
