- name: install nodej -c++
  ansible.builtin.yum:
    name:
      - nodejs
      - make
      - gcc-c++
- name: create roboshop user
  ansible.builtin.user:
    name: roboshop

- name: Download cataloge files
  ansible.builtin.import_role:
    name: common
    tasks_from: download

- name: Remove file html old web pages
  ansible.builtin.file:
    path: /home/roboshop/catalouge
    state: absent

- name: Copy the HTML Files
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue/
    remote_src: yes
  become_user: roboshop

- name: Install NodejS Dependencies
  community.general.npm:
    path: /home/roboshop/catalogue
  become_user: roboshop