- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/mongodb/archive/main.zip
    dest: /tmp
    remote_src: yes